// Generated by gencpp from file cartographer_ros_msgs/SubmapList.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_GENERIC_MSGS_MESSAGE_SUBMAPLIST_H
#define CARTOGRAPHER_GENERIC_MSGS_MESSAGE_SUBMAPLIST_H


#include <string>
#include <vector>
#include <map>

#include "cartographer_generic_msgs/Header.h"
#include "cartographer_generic_msgs/SubmapEntry.h"

namespace cartographer_generic_msgs
{

struct SubmapList
{


  SubmapList()
    : header()
    , submap()  {
    }

  Header header;
  std::vector< ::cartographer_generic_msgs::SubmapEntry >  submap;

  typedef boost::shared_ptr< ::cartographer_generic_msgs::SubmapList > Ptr;
  typedef boost::shared_ptr< ::cartographer_generic_msgs::SubmapList const> ConstPtr;

}; // struct SubmapList


typedef boost::shared_ptr< ::cartographer_generic_msgs::SubmapList > SubmapListPtr;
typedef boost::shared_ptr< ::cartographer_generic_msgs::SubmapList const> SubmapListConstPtr;

}

#endif // CARTOGRAPHER_GENERIC_MSGS_MESSAGE_SUBMAPLIST_H
