// Generated by gencpp from file cartographer_ros_msgs/SubmapQueryRequest.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_GENERIC_MSGS_MESSAGE_SUBMAPQUERYREQUEST_H
#define CARTOGRAPHER_GENERIC_MSGS_MESSAGE_SUBMAPQUERYREQUEST_H


#include <string>
#include <vector>
#include <map>

namespace cartographer_generic_msgs
{

struct SubmapQueryRequest
{


  SubmapQueryRequest()
    : trajectory_id(0)
    , submap_index(0)  {
    }


   int32_t trajectory_id;
   int32_t submap_index;

  typedef boost::shared_ptr< ::cartographer_generic_msgs::SubmapQueryRequest > Ptr;
  typedef boost::shared_ptr< ::cartographer_generic_msgs::SubmapQueryRequest const> ConstPtr;

}; // struct SubmapQueryRequest

typedef boost::shared_ptr< ::cartographer_generic_msgs::SubmapQueryRequest > SubmapQueryRequestPtr;
typedef boost::shared_ptr< ::cartographer_generic_msgs::SubmapQueryRequest const> SubmapQueryRequestConstPtr;

}

#endif // CARTOGRAPHER_GENERIC_MSGS_MESSAGE_SUBMAPQUERYREQUEST_H
