// Generated by gencpp from file cartographer_ros_msgs/SubmapQuery.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_GENERIC_MSGS_MESSAGE_SUBMAPQUERY_H
#define CARTOGRAPHER_GENERIC_MSGS_MESSAGE_SUBMAPQUERY_H


#include <cartographer_generic_msgs/SubmapQueryRequest.h>
#include <cartographer_generic_msgs/SubmapQueryResponse.h>


namespace cartographer_generic_msgs
{

struct SubmapQuery
{

typedef SubmapQueryRequest Request;
typedef SubmapQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SubmapQuery
} // namespace cartographer_generic_msgs


#endif // CARTOGRAPHER_GENERIC_MSGS_MESSAGE_SUBMAPQUERY_H
